/**
 * @file mainwindow.hpp
 * @brief Main window and UI glue for the circuit editor GUI.
 *
 * This header declares the MainWindow class which owns the main UI
 * elements and the central `GridWidget` used for drawing and editing
 * circuit components. It also contains slots used by the toolbar actions
 * to change the selected component type and to save the current
 * circuit as a netlist.
 */

#ifndef MAINWINDOW_HPP
#define MAINWINDOW_HPP

#include <QActionGroup>
#include <QMainWindow>
#include <QHash>
#include <QPair>

#include "gridwidget.hpp"

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

/**
 * @class MainWindow
 * @brief Application main window.
 *
 * The MainWindow class is responsible for creating and wiring up the
 * GUI: it holds the central `GridWidget`, manages the action group for
 * component selection, and provides slots that respond to UI events such
 * as toggling component buttons and saving the netlist to a file.
 */
class MainWindow : public QMainWindow {
  Q_OBJECT

 public:
  /**
   * @brief Construct a new MainWindow.
   * @param parent Optional parent widget (default: nullptr).
   */
  MainWindow(QWidget* parent = nullptr);

  /**
   * @brief Destroy the MainWindow and release owned resources.
   */
  ~MainWindow();

 private slots:

  /**
   * @brief Slot invoked when one of the component selection actions is toggled.
   * @param checked True if the action was checked (selected), false otherwise.
   *
   * When an action is toggled on, this slot makes sure other actions are
   * unchecked and instructs the `GridWidget` to use the selected component
   * type for subsequent drawing operations.
   */
  void onActionToggled(bool checked);

  /**
   * @brief Slot called when the `GridWidget` clears the current component type.
   *
   * This allows the MainWindow to update the UI (uncheck actions) to reflect
   * that no component type is currently selected.
   */
  void onComponentTypeCleared();

  /**
   * @brief Save the current circuit to a netlist file.
   *
   * Presents a Save dialog and writes the circuit netlist using the
   * information provided by the `GridWidget`.
   */
  void onSaveAs();

  /**
   * @brief Run simulation without saving a netlist and update tooltips.
   */
  void onRunSimulation();

  /**
   * @brief Open a file dialog to load a circuit file (Falstad format).
   */
  void onOpenFile();

  /**
   * @brief Configure simulation parameters (DC/AC, frequency).
   */
  void onConfigureSimulation();

 private:
  enum class SimulationType { DC, AC };
  SimulationType simulationType = SimulationType::DC;
  double acFrequency = 50.0;

  struct NetlistData {
    QString content;
    QHash<int, QPair<QString, int>> compOrder;
    QHash<QPoint, int> pointToNodeIndex;
  };

  NetlistData generateNetlistData(const QVector<GuiComponent>& components);
  QString generateFalstadContent(const QVector<GuiComponent>& components);

  /** Pointer to the UI generated by Qt Designer (ui_mainwindow.h). */
  Ui::MainWindow* ui;

  /** Action group containing the component selection actions. */
  QActionGroup* actionGroup;

  /** The central grid widget used to draw and edit components. */
  GridWidget* gridWidget;
};

#endif  // MAINWINDOW_HPP
